spring.datasource.url=jdbc:postgresql://localhost:5432/egc
spring.datasource.username=postgres
spring.datasource.password=mknic123
spring.jpa.hibernate.ddl-auto=update
server.port=8080
file.upload-dir=uploads

# JSP view resolver
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp